### ISSUE TITLE
add config schema

### ISSUE THREAD

**Issue by stolarczyk** [pepkit/divvy#54]
Add config schema to use validation feature in yacman 0.8.0 (https://github.com/databio/yacman/pull/44)

**Comment by stolarczyk** [comment]
right now the config schema just requires `compute_packages` section to be present and asserts the _structure_ of the `adapters` and `compute_packages`. 
Do we want to add more restrictions? For example?
- require `compute_packages.default` to be defined
- require `submission_template` and `submission_command` for every package?

```yaml
compute_packages: <-- require?
  default:
    submission_template: templates/local_template.sub  <-- require?
    submission_command: sh  <-- require?
```
