### ISSUE TITLE
add a more strict schema

### ISSUE THREAD

**Issue by stolarczyk** [pepkit/divvy#58]
right now the config schema just requires `compute_packages` section to be present and asserts the _structure_ of the `adapters` and `compute_packages`. 
Do we want to add more restrictions? For example:
- require `compute_packages.default` to be defined
- require `submission_template` and `submission_command` for every package?

```yaml
compute_packages:
  default: <-- require?
    submission_template: templates/local_template.sub  <-- require?
    submission_command: sh  <-- require?
```

_Originally posted by @stolarczyk in https://github.com/pepkit/divvy/issues/54#issuecomment-786871458_
